config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :routes do
      resources :points
    end
  end

  resources :towns

  match 'login/:token' => 'fb#login', via: [:get, :post]
  match 'login' => 'fb#login', via: [:get, :post]
  match 'index' => 'fb#index', via: [:get, :post]
  get 'place/:city' => 'fb#place'
  post 'place' => 'fb#place'
  match 'create_point' => 'fb#insert_point',via: [:get, :post]

  root 'fb#hello'

end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :town, dependent: :destroy
  belongs_to :route, dependent: :destroy
  has_one :user, through: :route

end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to user_route_point_path(params[:user_id],params[:route_id],@point), notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to user_route_point_path(params[:user_id],params[:point_id],@point), notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to user_route_points_path, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:date, :route_id, :town_id)
    end
end

app/views/points/_form.html.erb
<%= form_for(@point, url: @point.new_record? ? user_route_points_path(params[:user_id], params[:route_id] ) : user_route_point_path(params[:user_id], params[:route_id]) ) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :route_id %><br>
    <%= f.text_field :route_id %>
  </div>
  <div class="field">
    <%= f.label :town_id %><br>
    <%= f.text_field :town_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Listing points</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Route</th>
      <th>Town</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.date %></td>
        <td><%= point.route.user.name %></td>
        <td><%= point.town.name %></td>
        <td><%= link_to 'Show', user_route_point_path(params[:user_id],params[:route_id],point) %></td>
        <td><%= link_to 'Edit', edit_user_route_point_path(params[:user_id],params[:route_id],point) %></td>
        <td><%= link_to 'Destroy', user_route_path(params[:user_id], point), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_user_route_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', user_route_points_path(params[:user_id],params[:route_id]) %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @point.date %>
</p>

<p>
  <strong>Route:</strong>
  <%= @point.route %>
</p>

<p>
  <strong>Town:</strong>
  <%= @point.town.name %>
</p>

<%= link_to 'Edit', edit_user_route_point_path(params[:user_id],params[:route_id],@point) %> |
<%= link_to 'Back', user_route_points_path(params[:user_id],params[:route_id]) %>