config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :routes do
      resources :points
    end
  end

  resources :towns

  match 'login/:token' => 'fb#login', via: [:get, :post]
  match 'login' => 'fb#login', via: [:get, :post]
  match 'index' => 'fb#index', via: [:get, :post]
  get 'place/:city' => 'fb#place'
  post 'place' => 'fb#place'
  match 'create_point' => 'fb#insert_point',via: [:get, :post]

  root 'fb#hello'

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  has_many :points, dependent: :destroy
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to user_route_path(params[:user_id],@route), notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to user_route_path(params[:user_id],@route), notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:user_id)
    end
end

app/views/routes/_form.html.erb
<%= form_for(@route, url: @route.new_record? ? user_routes_path : new_user_route_path ) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', user_route_path(params[:user_id],@route) %> |
<%= link_to 'Back', user_routes_path(params[:user_id],@route) %>

app/views/routes/index.html.erb
<h1>Listing routes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.user.name %></td>
        <td><%= link_to 'Show', user_route_path(params[:user_id],route) %></td>
        <td><%= link_to 'Edit', edit_user_route_path(params[:user_id],route) %></td>
        <td><%= link_to 'Destroy', user_route_path(params[:user_id],route), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_user_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', user_routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @route.user.name %>
  <% @route.points.each do |point| %>
  	<%= point %>
  	<% end %>
</p>
<p>

</p>

<%= link_to 'Edit', edit_user_route_path(params[:user_id],@route) %> |
<%= link_to 'Back', user_routes_path %>