config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :routes do
      resources :points
    end
  end

  resources :towns

  match 'login/:token' => 'fb#login', via: [:get, :post]
  match 'login' => 'fb#login', via: [:get, :post]
  match 'index' => 'fb#index', via: [:get, :post]
  get 'place/:city' => 'fb#place'
  post 'place' => 'fb#place'
  match 'create_point' => 'fb#insert_point',via: [:get, :post]

  root 'fb#hello'

end

app/models/town.rb
class Town < ActiveRecord::Base
  has_many :points, dependent: :destroy
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_town, only: [:show, :edit, :update, :destroy]

  # GET /towns
  # GET /towns.json
  def index
    @towns = Town.all
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
  end

  # GET /towns/new
  def new
    @town = Town.new
  end

  # GET /towns/1/edit
  def edit
  end

  # POST /towns
  # POST /towns.json
  def create
    @town = Town.new(town_params)

    respond_to do |format|
      if @town.save
        format.html { redirect_to @town, notice: 'Town was successfully created.' }
        format.json { render :show, status: :created, location: @town }
      else
        format.html { render :new }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /towns/1
  # PATCH/PUT /towns/1.json
  def update
    respond_to do |format|
      if @town.update(town_params)
        format.html { redirect_to @town, notice: 'Town was successfully updated.' }
        format.json { render :show, status: :ok, location: @town }
      else
        format.html { render :edit }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town.destroy
    respond_to do |format|
      format.html { redirect_to towns_url, notice: 'Town was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town
      @town = Town.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def town_params
      params.require(:town).permit(:name, :api_id, :route_id)
    end
end

app/views/towns/_form.html.erb
<%= form_for(@town) do |f| %>
  <% if @town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% @town.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "API_ID" %><br>
    <%= f.text_field :api_id %>
  </div>
  <div class="field">
    <%= f.label :route_id %><br>
    <%= f.text_field :route_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towns/edit.html.erb
<h1>Editing town</h1>

<%= render 'form' %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<h1>Listing towns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Api</th>
      <th>Route</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @towns.each do |town| %>
      <tr>
        <td><%= town.name %></td>
        <td><%= town.api_id %></td>
        <td><%= town.route %></td>
        <td><%= link_to 'Show', town %></td>
        <td><%= link_to 'Edit', edit_town_path(town) %></td>
        <td><%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Town', new_town_path %>

app/views/towns/new.html.erb
<h1>New town</h1>

<%= render 'form' %>

<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @town.name %>
</p>

<p>
  <strong>Api:</strong>
  <%= @town.api_id %>
</p>

<p>
  <strong>Route:</strong>
  <%= @town.route %>
</p>

<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>